### non-normalized inputs

In [1]:
import tensorflow as tf
import numpy as np


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101): # step은 0~100까지 
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  219817930000.0 
Prediction:
 [[331278.06]
 [666924.8 ]
 [524640.  ]
 [367761.88]
 [433431.88]
 [437082.56]
 [400598.4 ]
 [510051.6 ]]
1 Cost:  2.415096e+26 
Prediction:
 [[-1.0962219e+13]
 [-2.2068073e+13]
 [-1.7360157e+13]
 [-1.2169378e+13]
 [-1.4342262e+13]
 [-1.4462977e+13]
 [-1.3255820e+13]
 [-1.6877293e+13]]
2 Cost:  inf 
Prediction:
 [[3.6335760e+20]
 [7.3147613e+20]
 [5.7542587e+20]
 [4.0337049e+20]
 [4.7539368e+20]
 [4.7939499e+20]
 [4.3938209e+20]
 [5.5942075e+20]]
3 Cost:  inf 
Prediction:
 [[-1.2043979e+28]
 [-2.4245765e+28]
 [-1.9073269e+28]
 [-1.3370259e+28]
 [-1.5757565e+28]
 [-1.5890193e+28]
 [-1.4563912e+28]
 [-1.8542756e+28]]
4 Cost:  inf 
Prediction:
 [[3.9921395e+35]
 [8.0365871e+35]
 [6.3220924e+35]
 [4.4317532e+35]
 [5.2230580e+35]
 [5.2670193e+35]
 [4.8274056e+35]
 [6.1462471e+35]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


### solution
> - min_max_scaler를 이용한 normalized
> - rugularization strength 부여

#### xy = MinMaxScaler(xy) 이용

In [2]:
import tensorflow as tf
import numpy as np


def MinMaxScaler(data):
    numerator = data - np.min(data, axis=0) # axis=0 => 행 기준
    denominator = np.max(data, axis=0) - np.min(data, axis=0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7) # 1e-7은 0으로 나누는것을 막기 위함


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  7.2467103 
Prediction:
 [[-3.6686876 ]
 [-2.3512933 ]
 [-2.0603585 ]
 [-1.8020444 ]
 [-2.013754  ]
 [-1.9253919 ]
 [-0.90982795]
 [-0.7647189 ]]
1 Cost:  7.246179 
Prediction:
 [[-3.6685503 ]
 [-2.3511639 ]
 [-2.0602505 ]
 [-1.8019607 ]
 [-2.0136547 ]
 [-1.9252961 ]
 [-0.90976524]
 [-0.76465845]]
2 Cost:  7.245648 
Prediction:
 [[-3.6684132 ]
 [-2.3510346 ]
 [-2.0601425 ]
 [-1.8018768 ]
 [-2.013555  ]
 [-1.9252002 ]
 [-0.90970254]
 [-0.76459795]]
3 Cost:  7.2451177 
Prediction:
 [[-3.668276  ]
 [-2.3509052 ]
 [-2.0600348