In [3]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np

### multivariable
H(x1,x2,x3) = w1x1+w2x2+w3x3 +b

### Simple Array

H(X) = XW : matrix 형태

[5,3] = [인스턴스 개수, 변수 개수]


In [5]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost) # w변수 update함

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  11366.697 
Prediction:
 [63.399445 66.89691  71.169106 72.95558  52.27266 ]
100 Cost:  14.44982 
Prediction:
 [157.79507 180.61832 183.08237 194.84927 139.06029]
200 Cost:  13.798487 
Prediction:
 [157.65802 180.7116  183.03949 194.82513 139.17688]
300 Cost:  13.181091 
Prediction:
 [157.52455 180.80237 182.99771 194.8018  139.29025]
400 Cost:  12.595747 
Prediction:
 [157.39458 180.89078 182.957   194.77919 139.40051]
500 Cost:  12.040855 
Prediction:
 [157.26802 180.97687 182.91736 194.75734 139.50772]
600 Cost:  11.514662 
Prediction:
 [157.14474 181.06068 182.8787  194.73619 139.61198]
700 Cost:  11.015831 
Prediction:
 [157.02472 181.1423  182.84103 194.71573 139.71336]
800 Cost:  10.542796 
Prediction:
 [156.9078  181.22177 182.80432 194.69597 139.81192]
900 Cost:  10.094267 
Prediction:
 [156.79393 181.29913 182.76855 194.67685 139.90775]
1000 Cost:  9.668946 
Prediction:
 [156.68306 181.37448 182.7337  194.6584  140.00093]
1100 Cost:  9.265625 
Prediction:
 [156.57506 

In [7]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) # 필요에 따라 인스턴스 추가 될 경우 마음대로 추가할 수 있도록 None
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b # 매트릭스의 곱

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  117902.875 
Prediction:
 [[-154.35013]
 [-180.54848]
 [-180.17714]
 [-198.78589]
 [-134.5047 ]]
100 Cost:  2.8945484 
Prediction:
 [[150.37016]
 [185.6046 ]
 [180.65036]
 [194.14505]
 [144.75446]]
200 Cost:  2.7927918 
Prediction:
 [[150.42041]
 [185.56975]
 [180.66518]
 [194.16019]
 [144.70497]]
300 Cost:  2.696214 
Prediction:
 [[150.46924]
 [185.53577]
 [180.67957]
 [194.17497]
 [144.65674]]
400 Cost:  2.604525 
Prediction:
 [[150.51674]
 [185.50279]
 [180.69357]
 [194.18948]
 [144.60974]]
500 Cost:  2.5174606 
Prediction:
 [[150.56291]
 [185.47069]
 [180.70714]
 [194.20369]
 [144.56393]]
600 Cost:  2.4347954 
Prediction:
 [[150.6078 ]
 [185.43947]
 [180.7203 ]
 [194.21759]
 [144.51929]]
700 Cost:  2.3563247 
Prediction:
 [[150.65144]
 [185.40913]
 [180.73312]
 [194.2312 ]
 [144.47578]]
800 Cost:  2.2817757 
Prediction:
 [[150.69386]
 [185.3796 ]
 [180.74556]
 [194.24455]
 [144.43338]]
900 Cost:  2.2109628 
Prediction:
 [[150.73512]
 [185.35088]
 [180.75763]
 [194.25761]
 [